// Code generated by aocgen; DO NOT EDIT.
package year2018

import (
	"strconv"
)

type Day01 struct{}

func (p Day01) PartA(lines []string) any {
	sum := 0
	for _, line := range lines {
		if line == "" {
			continue
		}

		changeSign := rune(line[0])
		number, err := strconv.Atoi(line[1:])
		if err != nil {
			panic(err)
		}

		switch changeSign {
		case '+': sum += number
		case '-': sum -= number

		}

	}

	return sum
}

func (p Day01) PartB(lines []string) any {
	return "implement_me"
}
