// Code generated by aocgen; DO NOT EDIT.
package year2023

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestDay03(t *testing.T) {
	day03 := Day03{}
	input := []string{
		"467..114..",
		"...*......",
		"..35..633.",
		"......#...",
		"617*......",
		".....+.58.",
		"..592.....",
		"......755.",
		"...$.*....",
		".664.598..",
	}

	t.Run("partA", func(t *testing.T) {
		result := day03.PartA(input)

		assert.Equal(t, 4361, result)
	})

	t.Run("partB", func(t *testing.T) {
		result := day03.PartB(input)
		assert.Equal(t, 467835, result)
	})
}
