// Code generated by aocgen; DO NOT EDIT.
package year2023

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestDay06(t *testing.T) {
	day06 := Day06{}
	input := []string{
		"Time:      7  15   30",
		"Distance:  9  40  200",
	}

	t.Run("partA", func(t *testing.T) {
		result := day06.PartA(input)

		assert.Equal(t, 288, result)
	})

	t.Run("partB", func(t *testing.T) {
		result := day06.PartB(input)
		assert.Equal(t, 71503, result)
	})
}
