// Code generated by aocgen; DO NOT EDIT.
package year2023

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestDay07(t *testing.T) {
	day07 := Day07{}
	input := []string{
		"32T3K 765",
		"T55J5 684",
		"KK677 28",
		"KTJJT 220",
		"QQQJA 483",
	}

	t.Run("partA", func(t *testing.T) {
		result := day07.PartA(input)

		assert.Equal(t, 6440, result)
	})

	t.Run("partB", func(t *testing.T) {
		result := day07.PartB(input)
		assert.Equal(t, 5905, result)
	})
}
