// Code generated by aocgen; DO NOT EDIT.
package year2023

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestDay01(t *testing.T) {
	day01 := Day01{}
	input := []string{
		"1abc2",
		"pqr3stu8vwx",
		"a1b2c3d4e5f",
		"treb7uchet",
	}

	t.Run("partA", func(t *testing.T) {
		result := day01.PartA(input)

		assert.Equal(t, 142, result)
	})

	t.Run("partB", func(t *testing.T) {
		inputPartB := []string {
			"two1nine",
			"eightwothree",
			"abcone2threexyz",
			"xtwone3four",
			"4nineeightseven2",
			"zoneight234",
			"7pqrstsixteen",
		}

		result := day01.PartB(inputPartB)
		assert.Equal(t, 281, result)
	})
	t.Run("partB 2", func(t *testing.T) {
		inputPartB := []string {
			"2911threeninesdvxvheightwobm",
		}

		result := day01.PartB(inputPartB)
		assert.Equal(t, 22, result)
	})
}
