// Code generated by aocgen; DO NOT EDIT.
package year2022

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestDay05(t *testing.T) {
	day05 := Day05{}
	input := []string{}

	t.Run("partA", func(t *testing.T) {
		result := day05.PartA(input)

		assert.Equal(t, "implement_me", result)
	})

	t.Run("partB", func(t *testing.T) {
		result := day05.PartB(input)
		assert.Equal(t, "implement_me", result)
	})
}
