// Code generated by aocgen; DO NOT EDIT.
package year2022

type Day05 struct{}

func (p Day05) PartA(lines []string) any {
	return "implement_me"
}

func (p Day05) PartB(lines []string) any {
	return "implement_me"
}
