// Code generated by aocgen; DO NOT EDIT.
package year2019

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestDay01(t *testing.T) {
	day01 := Day01{}
	input := []string{}

	t.Run("partA", func(t *testing.T) {
		result := day01.PartA(input)

		assert.Equal(t, "implement_me", result)
	})

	t.Run("partB", func(t *testing.T) {
		result := day01.PartB(input)
		assert.Equal(t, "implement_me", result)
	})
}
