// Code generated by aocgen; DO NOT EDIT.
package year2021

import (
	"strconv"
	"strings"
)

type Day02 struct{}

func (p Day02) PartA(lines []string) any {
	submarineHorizontalPos := 0
	submarineDepthPos := 0

	for _, line := range lines {
		if line == "" {
			continue
		}

		lineSplitted := strings.Split(line, " ")
		action := lineSplitted[0]
		valueStr := lineSplitted[1]
		value,err := strconv.Atoi(valueStr)
		if err != nil {
			panic("Invalid input")
		}

		switch action {
		case "forward": {
			submarineHorizontalPos += value
		}
		case "up": {
			submarineDepthPos -= value
		}
		case "down" : {
			submarineDepthPos += value
		}
		default: panic("Invalid action in input")
		}
	}
	return submarineHorizontalPos * submarineDepthPos
}

func (p Day02) PartB(lines []string) any {
	submarineHorizontalPos := 0
	submarineDepthPos := 0
	submarineAimPos := 0

	for _, line := range lines {
		if line == "" {
			continue
		}

		lineSplitted := strings.Split(line, " ")
		action := lineSplitted[0]
		valueStr := lineSplitted[1]
		value,err := strconv.Atoi(valueStr)
		if err != nil {
			panic("Invalid input")
		}

		switch action {
		case "forward": {
			submarineHorizontalPos += value
			submarineDepthPos += submarineAimPos * value
		}
		case "up": {
			submarineAimPos -= value
		}
		case "down" : {
			submarineAimPos += value
		}
		default: panic("Invalid action in input")
		}
	}
	return submarineHorizontalPos * submarineDepthPos
	return "implement_me"
}
