// Code generated by aocgen; DO NOT EDIT.
package year2021

type Day04 struct{}

func (p Day04) PartA(lines []string) any {
	return "implement_me"
}

func (p Day04) PartB(lines []string) any {
	return "implement_me"
}
