// Code generated by aocgen; DO NOT EDIT.
package year2020

type Day03 struct{}

func (p Day03) PartA(lines []string) any {
	return "implement_me"
}

func (p Day03) PartB(lines []string) any {
	return "implement_me"
}
