// Code generated by aocgen; DO NOT EDIT.
package year2020

import (
	"strconv"
)

type Day01 struct{}

func (p Day01) PartA(lines []string) any {
	numbers := extractInts(lines)

	for _, currentNumber := range numbers {
		for _, secondNumber := range numbers {
			if currentNumber+secondNumber == 2020 {
				return currentNumber * secondNumber
			}
		}
	}

	panic("Did not find two numbers which sums to 2020")
}

func extractInts(lines []string) []int {
	var numbers []int
	for _, number := range lines {
		if number == "" {
			continue
		}

		numberInt, err := strconv.Atoi(number)
		if err != nil {
			panic(err)
		}
		numbers = append(numbers, numberInt)
	}
	return numbers
}

func (p Day01) PartB(lines []string) any {
	numbers := extractInts(lines)

	for _, currentNumber := range numbers {
		for _, secondNumber := range numbers {
			for _, thirdNumber := range numbers {
				if currentNumber+secondNumber + thirdNumber == 2020 {
					return currentNumber * secondNumber * thirdNumber
				}
			}
		}
	}

	panic("Did not find two numbers which sums to 2020")
}
