// Code generated by aocgen; DO NOT EDIT.
package year2020

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestDay03(t *testing.T) {
	day03 := Day03{}
	input := []string{}

	t.Run("partA", func(t *testing.T) {
		result := day03.PartA(input)

		assert.Equal(t, "implement_me", result)
	})

	t.Run("partB", func(t *testing.T) {
		result := day03.PartB(input)
		assert.Equal(t, "implement_me", result)
	})
}
